source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MWPhotoBrowser_Example'  do
  pod "MWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Tests' do
  pod "MWPhotoBrowser", :path => "../"

  pod 'Specta'
  pod 'Expecta'
   pod 'FBSnapshotTestCase', '~> 1.8.1'
  pod 'Expecta+Snapshots'
end
